-- 1. Table for Contact Form Submissions ("Send Us a Message")
CREATE TABLE IF NOT EXISTS contact_submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  full_name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  subject TEXT,
  message TEXT NOT NULL
);

-- Enable RLS & allow public form submission
ALTER TABLE contact_submissions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public insert to contact_submissions" ON contact_submissions;
CREATE POLICY "Allow public insert to contact_submissions" 
ON contact_submissions FOR INSERT 
WITH CHECK (true);

-- 2. Table for Donations ("Make a Donation")
CREATE TABLE IF NOT EXISTS donations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  full_name TEXT NOT NULL,
  email TEXT NOT NULL,
  mobile_number TEXT NOT NULL,
  amount NUMERIC NOT NULL,
  seva_category TEXT,
  payment_id TEXT,
  order_id TEXT,
  status TEXT DEFAULT 'pending'
);

-- Enable RLS & allow public form submission
ALTER TABLE donations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public insert to donations" ON donations;
CREATE POLICY "Allow public insert to donations" 
ON donations FOR INSERT 
WITH CHECK (true);
